nameOverride: "explana-api"
replicaCount: 1
image:
  repository: "myawesomeapps/explana-api"
  tag: "1.0"
service:
  name: "explana-api-svc"
  port: 80
  targetPort: 8080
  type: ClusterIP
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi
env:
  - name: MONGO_HOST
    value: mongo-svc
envFrom:
  - configMapRef:
      name: db-configmap
ingress:
  enabled: true
  hostname: "api.explana.awesomeapps.cloud"
  path: "/"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: api.explana.awesomeapps.cloud
    external-dns.alpha.kubernetes.io/ttl: "120"
  tls:
    - hosts:
      - "api.explana.awesomeapps.cloud"
      secretName: "explanapp-api-tls"
