apiVersion: v1
kind: List
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: video-extract-api
    namespace: argocd
  spec:
    project: default
    source:
      repoURL: 'https://github.com/emvnuel/deployments'
      path: 'common-chart'
      targetRevision: HEAD
      helm:
        valueFiles:
          - ../video-extract/api/values.yaml
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: 'video-extract'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: video-extract-front
    namespace: argocd
  spec:
    project: default
    source:
      repoURL: 'https://github.com/emvnuel/deployments'
      path: 'common-chart'
      targetRevision: HEAD
      helm:
        valueFiles:
          - ../video-extract/front/values.yaml
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: 'video-extract'
    syncPolicy:
      automated:
        prune: true
        selfHeal: true