nameOverride: "explana-client"
replicaCount: 1
image:
  repository: "myawesomeapps/explana-client"
  tag: "1.1"
service:
  name: "explana-client-svc"
  port: 80
  targetPort: 8080
  type: ClusterIP
resources:
  limits:
    cpu: 100m
    memory: 512Mi
ingress:
  enabled: true
  hostnames: "explana.awesomeapps.cloud"
  cloudflare_proxied: true
  tls:
    enabled: true
