fullnameOverride: n8n-app

image:
  repository: n8nio/n8n
  tag: 2.4.6

# Ingress deployment for n8n.
main:
  config:
    n8n:
      hide_usage_page: true
    db:
      type: postgresdb
      postgresdb:
        host: postgres-cluster-rw.postgres.svc.cluster.local
        port: 5432
        database: app_database
        user: app_user
  extraEnv:
    GENERIC_TIMEZONE: "America/Sao_Paulo"
    N8N_ENCRYPTION_KEY:
      valueFrom:
        secretKeyRef:
          name: n8n-app-secret
          key: encryption-key
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: n8n-db-secret
          key: password
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
  persistence:
    # If true, use a Persistent Volume Claim, If false, use emptyDir
    type: dynamic
    enabled: true
    annotations:
      helm.sh/resource-policy: keep
      argocd.argoproj.io/sync-options: Prune=false
    storageClass: local-path
    accessModes:
      - ReadWriteOnce
    # Persistent Volume size
    size: 1Gi

ingress:
  enabled: true
  className: nginx
  annotations:
    external-dns.alpha.kubernetes.io/hostname: n8n.awesomeapps.cloud
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: n8n.awesomeapps.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: n8n-ingress-tls
      hosts:
        - n8n.awesomeapps.cloud
