apiVersion: v2
name: copilot-api
description: Copilot API deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: common-chart
    version: 0.1.0
    repository: "file://../common-chart"
