nameOverride: "video-extract-backend"
replicaCount: 1
image:
  repository: "myawesomeapps/video-extract-api"
  tag: "1.0"
service:
  name: "video-extract-backend-svc"
  port: 80
  targetPort: 8000
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi
env:
  - name: PYTHONDONTWRITEBYTECODE
    value: "1"
  - name: PYTHONUNBUFFERED
    value: "1"
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
ingress:
  enabled: true
  hostnames: "api.video-extract.awesomeapps.cloud"
  tls:
    enabled: true
