apiVersion: v2
name: payroll-front
description: Payroll Front deployment
type: application
version: 1.0.0
appVersion: "2.0"
dependencies:
  - name: common-chart
    version: 0.1.0
    repository: "file://../common-chart"
