common-chart:
  nameOverride: "payroll-front"
  replicaCount: 1
  image:
    repository: "myawesomeapps/payroll-front"
    tag: "2.3"
  service:
    name: "payroll-front-svc"
    port: 80
    targetPort: 3000
    type: ClusterIP
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
  configMap:
    enabled: true
    name: "payroll-front-config"
    data:
      NEXT_PUBLIC_PAYROLL_API_URL: "https://payroll.gambiarra.space/payroll"
  envFrom:
    - configMapRef:
        name: "payroll-front-config"
  ingress:
    enabled: true
    hostnames: "salario.gambiarra.space,www.salario.gambiarra.space"
    cloudflare_proxied: true
    tls:
      enabled: true
