apiVersion: v2
name: explana-api
description: Explana App API deployment
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: common-chart
    version: 0.1.0
    repository: "file://../../common-chart"
