common-chart:
  nameOverride: "landing-page"
  replicaCount: 1
  image:
    repository: "myawesomeapps/landing-page"
    tag: "2.0"
  service:
    name: "landing-page-svc"
    port: 80
    targetPort: 3000
    type: ClusterIP
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
  ingress:
    enabled: true
    hostnames: "gambiarra.space,www.gambiarra.space,www1.gambiarra.space"
    cloudflare_proxied: true
    tls:
      enabled: true
