apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common-chart.fullname" . }}
  labels:
    {{- include "common-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "common-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "common-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "common-chart.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if and .Values.probes.enabled .Values.probes.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.probes.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if and .Values.probes.enabled .Values.probes.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.probes.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
