{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "common-chart.fullname" . }}
  labels:
    {{- include "common-chart.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge .Values.ingress.extraAnnotations .Values.ingress.annotations -}}
    {{- if .Values.ingress.hostnames -}}
    {{-   $_ := set $annotations "external-dns.alpha.kubernetes.io/hostname" .Values.ingress.hostnames -}}
    {{- end -}}
    {{- if .Values.ingress.cloudflare_proxied -}}
    {{-   $_ := set $annotations "external-dns.alpha.kubernetes.io/cloudflare-proxied" "true" -}}
    {{- end -}}
    {{- toYaml $annotations | nindent 4 }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- $hostnames := .Values.ingress.hostnames | splitList "," -}}
        {{- range $hostnames }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "common-chart.fullname" .)) }}
  {{- end }}
  rules:
    {{- $hostnames := .Values.ingress.hostnames | splitList "," -}}
    {{- range $hostnames }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "common-chart.serviceName" $ }}
                port:
                  name: http
    {{- end }}
{{- end }}