apiVersion: apps/v1
kind: Deployment
metadata:
  name: payroll
  namespace: default
spec:
  selector:
    matchLabels:
      app: payroll
  template:
    metadata:
      labels:
        app: payroll
    spec:
      containers:
      - name: payroll
        image: myawesomeapps/payroll:1.11-multiarch
        env:
        - name: INSS_RANGES
          valueFrom:
            configMapKeyRef:
              name: payroll-config
              key: INSS_RANGES
        - name: IRRF_RANGES
          valueFrom:
            configMapKeyRef:
              name: payroll-config
              key: IRRF_RANGES
        - name: DEPENDENT_DEDUCTION_AMOUNT
          valueFrom:
            configMapKeyRef:
              name: payroll-config
              key: DEPENDENT_DEDUCTION_AMOUNT
        - name: INSS_RANGE_5_DISCOUNT_AMOUNT
          valueFrom:
            configMapKeyRef:
              name: payroll-config
              key: INSS_RANGE_5_DISCOUNT_AMOUNT
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payroll-svc
  namespace: default
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8080'
  labels:
    foo: bar
spec:
  type: ClusterIP
  selector:
    app: payroll
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payroll-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels:
    name: payroll-ingress
spec:
  tls:
    - hosts:
      - "payroll.labzzz.shop"
      secretName: "payroll-tls"
  rules:
  - host: payroll.labzzz.shop
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: payroll-svc
            port: 
              number: 8080 
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: payroll-config
    namespace: default
data:
    INSS_RANGES: '[{"index":1,"aliquot":0.075,"init_value":1412,"end_value":1412},{"index":2,"aliquot":0.09,"init_value":1412.01,"end_value":2666.68},{"index":3,"aliquot":0.12,"init_value":2666.69,"end_value":4000.03},{"index":4,"aliquot":0.14,"init_value":4000.04,"end_value":7786.02},{"index":5,"aliquot":0.14,"init_value":7786.03,"end_value":1000000}]'
    IRRF_RANGES: '[{"init_value":0,"end_value":2259.2,"aliquot":0,"deduction":0},{"init_value":2259.21,"end_value":2828.65,"aliquot":0.075,"deduction":169.44},{"init_value":2828.66,"end_value":3751.05,"aliquot":0.15,"deduction":381.44},{"init_value":3751.06,"end_value":4664.68,"aliquot":0.225,"deduction":662.77},{"init_value":4664.68,"end_value":1000000,"aliquot":0.275,"deduction":896}]'
    DEPENDENT_DEDUCTION_AMOUNT: "189.59"
    INSS_RANGE_5_DISCOUNT_AMOUNT: "908.85"